modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="atlaslib"
version="1.1.3"
displayName="Atlas Lib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/atlas-lib" #optional
updateJSONURL="https://github.com/SmileycorpMC/Atlas-Lib/blob/1.17/update.json"
credits="Smileycorp" #optional
authors="Smileycorp" #optional
description=""