modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="atlaslib"
version="1.1.1"
displayName="Atlas Lib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/atlas-lib" #optional
updateJSONURL=""
credits="Smileycorp" #optional
authors="Smileycorp" #optional
description=""